dist: trusty
language: generic

before_install:
  # Install Linuxbrew
  - test -d $HOME/.linuxbrew/bin || git clone https://github.com/Linuxbrew/brew.git $HOME/.linuxbrew
  - PATH="$HOME/.linuxbrew/bin:$PATH"
  - echo 'export PATH="$HOME/.linuxbrew/bin:$PATH"' >>~/.bash_profile
  - export MANPATH="$(brew --prefix)/share/man:$MANPATH"
  - export INFOPATH="$(brew --prefix)/share/info:$INFOPATH"
  - brew --version
  # Install Buck
  - brew tap facebook/fb
  - brew install buck
  - buck --version
  # Install GCC
  - brew install gcc

install:
  - mkdir $HOME/scripts && printf -- "--config\ncxx.ldflags=-B \"$(dirname $(which ld))\"\n--config\ncxx.ar=$(which ar)\n--config\ncxx.cc=$(which gcc)\n--config\ncxx.cpp=$(which gcc)\n--config\ncxx.cxx=$(which g++)\n--config\ncxx.cxxpp=$(which g++)\n--config\ncxx.ld=$(which g++)\n--config\nui.superconsole=DISABLED\n" > $HOME/scripts/buck_build_settings

script:
  - buck clean
  - buck build @$HOME/scripts/buck_build_settings connect-linux

branches:
  except:
    - gh-pages

cache:
  directories:
    - $HOME/.linuxbrew/
